// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJVOORj4o-Shb-UaAFWWMuyWHdJsxHpmY',
    appId: '1:536712562673:web:ebd7fbf2420902a457a650',
    messagingSenderId: '536712562673',
    projectId: 'evently-737fb',
    authDomain: 'evently-737fb.firebaseapp.com',
    storageBucket: 'evently-737fb.firebasestorage.app',
    measurementId: 'G-6NS46Z24Q5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7f9RXYunnBQlGIxnPEwNm5k8sNL68ip0',
    appId: '1:536712562673:android:6376bc0ed03e23d457a650',
    messagingSenderId: '536712562673',
    projectId: 'evently-737fb',
    storageBucket: 'evently-737fb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBD4AD1E5SDbPYmZSRrD95KJr8ncU0v_mw',
    appId: '1:536712562673:ios:d7af0f38e837830b57a650',
    messagingSenderId: '536712562673',
    projectId: 'evently-737fb',
    storageBucket: 'evently-737fb.firebasestorage.app',
    iosBundleId: 'com.example.evently',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBD4AD1E5SDbPYmZSRrD95KJr8ncU0v_mw',
    appId: '1:536712562673:ios:d7af0f38e837830b57a650',
    messagingSenderId: '536712562673',
    projectId: 'evently-737fb',
    storageBucket: 'evently-737fb.firebasestorage.app',
    iosBundleId: 'com.example.evently',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJVOORj4o-Shb-UaAFWWMuyWHdJsxHpmY',
    appId: '1:536712562673:web:6d42c127f77ee0f157a650',
    messagingSenderId: '536712562673',
    projectId: 'evently-737fb',
    authDomain: 'evently-737fb.firebaseapp.com',
    storageBucket: 'evently-737fb.firebasestorage.app',
    measurementId: 'G-XLTDCHQTCM',
  );
}
